### ISSUE TITLE
Try to reduce the number of dependencies. I see some functions that can be written independently or using base R.

### ISSUE THREAD

**Issue by jramirezv** [ccsosa/GapAnalysis#10]

**Comment by kauedesousa** [comment]
Example here https://github.com/ccsosa/GapAnalysis/issues/12#issuecomment-624083822

**Comment by ccsosa** [comment]
eooaoo and OccurrenceCounts.R are pending to transform to base. I wonder if we need to change those functions. Basically, OccurrenceCounts.R is doing well at filtering to use in the whole run.

**Comment by jramirezv** [comment]
I think we should transform OccurrenceCounts to base, and delete eooaoo. Deleting eooaoo also means removing it from summaryHTML.

**Comment by ccsosa** [comment]
Done. Just summaryHTML is using dplyr
