### ISSUE TITLE
Avoid use of dplyr

### ISSUE THREAD

**Issue by jramirezv** [ccsosa/GapAnalysis#12]
Avoid all dplyr function (this pkg is most to work with scripts and is always changing). All this dplyr things can be done with base R (I bit more complicated, but worth the pain). For example mutate_if() and filter. The first can be applied with a lapply() and the later with df[df$var == something, ].

**Comment by kauedesousa** [comment]
For example this:

```
nc <- dim(ecoReg@data)[[2]]

ecoReg@data[1:nc] <- lapply(ecoReg@data[1:nc], function(x){
  if (is.character(x)) {
    iconv(x, to = "UTF-8")
  }
})

```
Instead of this: 

```
ecoReg@data <- 
  ecoReg@data %>%
  dplyr::mutate_if(is.character, iconv, to = 'UTF-8')
```


And be sure that the slot "data" will always has this name.

**Comment by ccsosa** [comment]
Occurrences_count was converted to base. Testing is pending

**Comment by jramirezv** [comment]
Not sure why this has been closed. I still see `dplyr` in list of dependencies. Reopening it.

**Comment by dcarver1** [comment]
I removed dplyr function from FCSex and FCSin

**Comment by ccsosa** [comment]
The unique code with dplyr is SummaryHTML.R @dcarver1, do you need dplyr for the rmd file step?

**Comment by dcarver1** [comment]
I should be able to drop it but I'll let you know for sure this afternoon. Lots of meetings today :(

**Comment by jramirezv** [comment]
once you remove it from code, also remove from any `@importFrom` statements

**Comment by ccsosa** [comment]
There is just one @import From in SummaryHTML

**Comment by ccsosa** [comment]
@dcarver1  Thanks for removed dplyr functions from SummaryHTML
