### ISSUE TITLE
Review and fix README.md

### ISSUE THREAD

**Issue by jramirezv** [ccsosa/GapAnalysis#17]
There are some issues in the README.md (see for instance some of the code pieces won't run). Please review and ensure they work. Also it could probably be shortened. Few pointers here:

– make it shorter, less wordy. In each section just go to the point. The point of a README is that you can go through it very quickly, and get going with things.
– ensure it is consistent with final code and function names for package (test that every piece of code actually runs)
– including using less references. I suggest use only two: Ramirez-Villegas et al. 2010 and Khoury et al. 2019. If we want a third you can add Castaneda-Alvarez et al. (2016) but not more. Ramirez-Villegas et al. (2010) has to be at the top of reference list.
– use table format and not `x | y | z` as it can be confusing
– in the usage section: use the examples within the package so that people can copy-paste, instead of providing some cumbersome explanation about some other dataset that must be downloaded somewhere else. You can provide that, too, but at the bottom maybe in a section called 'Other examples'

**Comment by ColinKhoury** [comment]
Hi I made major fixes to align with paper. Basically done except for the dependencies and the examples part

**Comment by jramirezv** [comment]
Looks good. Reduced references (don't think we need to reference so many things –let's keep it focussed on the three most important papers: 2010 PLoS, 2016 NPlants, and 2019 EcoInd.

Also, some the function Gbuffer is an internal one, so I suggest that we remove it from the readme.

**Comment by ColinKhoury** [comment]
Juli re papers- really a few more are important in implementing all the steps:
Ramirez 2010 had SRSex, GRSex, ERSex
Castaneda updated ERSex
Khoury 2019 ecol updated SRSex, and added GRSin and ERSin, as well as indicator
Khoury 2019 Cucurbit and Capsicum added SRSin, and also added html
so Id like to keep them (or one of them, as I had in the refs) in

**Comment by jramirezv** [comment]
Ok, then. Add the minimum necessary, but then reference them in the right places, too. I just don't want to have a list of 20 references that the reader won't be able to read. We should have the main ones, so based on what you say I propose:

Ramirez-Villegas 2010
Castaneda-Alvarez 2016
Khoury 2019 Ecol Ind
Khoury 2019 Cucurbita (or Capsicum) but not both.

**Comment by ColinKhoury** [comment]
Yup will do. Its just one more ref (Capsicum)

**Comment by ColinKhoury** [comment]
The only other paper which might be critical (depending on how Dan and Chrys built the pull of the ecoregions and protected areas dbs) is 
Khoury CK, Amariles D, Soto JS, Diaz MV, Sotelo S, Sosa CC, Ramírez-Villegas J, Achicanoy HA, Castañeda-Álvarez NP, León B, and Wiersema JH (2019) Data for the calculation of an indicator of the comprehensiveness of conservation of useful wild plants. Data in Brief 22: 90-97. doi: 10.1016/j.dib.2018.11.125. https://doi.org/10.1016/j.dib.2018.11.125   
Data: http://dx.doi.org/10.17632/2jxj4k32m2.1  |  http://dx.doi.org/10.17632/2jxj4k32m2.2 

This is where the processed spatial layers were made open access

**Comment by jramirezv** [comment]
Yeah that can go into the help files of the package. My point here is not that this extra content is not relevant at all, but rather that that it doesn't need to go in the README file. The README should be clear, and very focussed on getting the user going, without overly complicating things with references or detailed explanations. Whoever needs more explanation can go to previous references, the new package paper, package help files, and other sources.

**Comment by ColinKhoury** [comment]
Ok! Will cease and desist!

**Comment by jramirezv** [comment]
Good. Look at the `raster` package README here https://github.com/rspatial/raster, `terra` (likely replacing `raster` in a few years https://github.com/rspatial/terra, and `ggplot2` https://github.com/tidyverse/ggplot2. Really focused on getting the user going.

**Comment by ColinKhoury** [comment]
ReadMe is just about ready except the installation and usage sections need work (Chrys, Dan)

**Comment by jramirezv** [comment]
I have fixed these now. Maybe we only need to remove `dplyr` once @dcarver1 has removed it from the code. But for the sake of moving forward I'll close this issue.
