### ISSUE TITLE
Produce ecological gap map for ERSex

### ISSUE THREAD

**Issue by ColinKhoury** [ccsosa/GapAnalysis#19]
The ex situ ecological gap map is created by mapping only the spatial areas within the distribution model of each taxon which are occupied by ecoregions not represented by G buffers

**Comment by jramirezv** [comment]
In summaryHTML

**Comment by ColinKhoury** [comment]
Dan's code currently does it in html process as an imbed but also writes out as rasters (important for making pretty pictures for articles; for making gap richness maps, etc.). I prefer these processes are done with their pertinent ex situ or in situ assessments, but am ok with them in HTLM process

**Comment by ColinKhoury** [comment]
but note these maps arent made yet (they are made for geographic, but not yet for ecological); will be a nice enhancement

**Comment by ccsosa** [comment]
canThey  be done using summaryHTML?

**Comment by ColinKhoury** [comment]
These have to be built still (Dan)

**Comment by dcarver1** [comment]
This has been integrated into the ERSex function. I will close this issue once the method is valid.
