### ISSUE TITLE
Produce ecological gap map for ERSin

### ISSUE THREAD

**Issue by ColinKhoury** [ccsosa/GapAnalysis#20]
The in situ ecological gap map is created by mapping only the spatial areas within the distribution model of each taxon which are occupied by ecoregions not represented at all in protected areas

**Comment by jramirezv** [comment]
In summaryHTML? Or do you mean a raster object as output?

**Comment by ColinKhoury** [comment]
Dan's code currently does it in html process as an imbed but also writes out as rasters (important for making pretty pictures for articles; for making gap richness maps, etc.). I prefer these processes are done with their pertinent ex situ or in situ assessments, but am ok with them in HTLM process

**Comment by ColinKhoury** [comment]
but note these maps arent made yet (they are made for geographic, but not yet for ecological); will be a nice enhancement

**Comment by jramirezv** [comment]
What do you think about something like this:
– ERS and GRS (for both in-situ and ex-situ) provide in addition to the table of species with the ERSex value, also provide a raster as output. 
– ExsituCompile and InsituCompile should return the two rasters (ERS and GRS) in addition to the table of metrics.
– SummaryHTML allows writing if user wants (writeRasters=TRUE).

This way the user can choose to write themselves the output of the analysis steps, whereas the SummaryHTML function will write the whole bunch if user wants to.

**Comment by ColinKhoury** [comment]
YES that's my preference

**Comment by ccsosa** [comment]
In-situ gap map is added in FCSin as the difference of protected areas and sdm

**Comment by ColinKhoury** [comment]
But Chrys- note that that is the geographic in situ gap map. we still need to produce the ecological insitu gap map, which is different (mapping only the spatial areas within the distribution model of each taxon which are occupied by ecoregions not represented at all in protected areas). This is for Dan

**Comment by ColinKhoury** [comment]
need to produce ecological in situ gap map

**Comment by dcarver1** [comment]
I'm reviewing the existing structure for the gap maps and will replecate in for the ecological gaps.

**Comment by dcarver1** [comment]
The gap map has been integrated into the ERSin function. I will close this issue once the process has been validated.

**Comment by dcarver1** [comment]
For what ever reason i'm getting a new error today when trying to convert the subset of the ecoregions present in the predicted presence area into a raster. 

eco3 <- fasterize::fasterize(eco2a, SdmMask) #field = 'ECO_ID_U')
Error in fasterize::fasterize(eco2a, SdmMask) : Not an S4 object.

st_to_sf produces an S3 method. fasterize only takes sf objects. It seems to be asking for a S4 sf object???  Hopefully this is just some silly mistake I am making because as I mention this was working yesterday

**Comment by ccsosa** [comment]
Dan, I fixed this issue. Please check again. It was an error at resampling. I fixed it and it is running
