### ISSUE TITLE
Move production of gap maps to Ex situ and In situ families of codes

### ISSUE THREAD

**Issue by ColinKhoury** [ccsosa/GapAnalysis#21]
Right now the production of the 2 existing (and 2 new proposed) gap maps are all done during the SummaryHTML process. Conceptually it would be nice if those maps were made within the Ex situ and In situ code families. I'm ok with leaving them where they are if others dont feel the same.

**Comment by jramirezv** [comment]
Doesnt make sense because it is all stored in memory. It has to be in summaryHTML.

**Comment by ColinKhoury** [comment]
fair enough but we also want to write them out as rasters (and Dan's process does so)
