### ISSUE TITLE
Add indicator.R code

### ISSUE THREAD

**Issue by ColinKhoury** [ccsosa/GapAnalysis#22]
Gapanalysis also provides code for the calculation of an indicator across assessed taxa, which can be applied at national, regional, global, or any other scale (Khoury et al., 2019b) (Equation 10). The indicator is calculated separately with regard to ex situ, in situ, and combined conservation, by deriving the proportion of taxa categorized as SC or LP out of all taxa.
Indicator = [((number of taxa whose FCSc-mean is ≥ 50)/(Total number of taxa )]*100   (Equation 10)

"need to get from Aichi code - https://github.com/CIAT-DAPA/UsefulPlants-Indicator/blob/develop/src/3_indicator/indicator.R

**Comment by ccsosa** [comment]
I included the function. Could you please check and add the values in @return @ColinKhoury @Dan?

**Comment by ccsosa** [comment]
Hi Colin, Could you please check if the documentation in the function is OK. I made the modifications that you requested.

**Comment by ColinKhoury** [comment]
Please fix issue on line 150. should be proportion_LP_SC  (not CP_SC)

**Comment by ccsosa** [comment]
Fixed

**Comment by ColinKhoury** [comment]
Remove the codes related to assign classes ex situ and in situ from indicator code (lines 85-115). These classes are assigned now in FCSex and FCSin codes

**Comment by ccsosa** [comment]
Fixed
