### ISSUE TITLE
Standardize names of codes and objects throughout code

### ISSUE THREAD

**Issue by ColinKhoury** [ccsosa/GapAnalysis#23]
See https://docs.google.com/spreadsheets/d/13biW9f8jfwceNvRJZIgJno2o1x64-yZ2yg8btNZ1LAs/edit#gid=0 for suggested names for processes. In green are my absolute must haves. Most all these changes have already been implemented.

Within codes, still work to be done to clean names, to:
better align with names in the google doc (e.g. SRSex_df, NOT srsEx_df)
better align across all code (do NOT start with a lowercase then put a capital (e.g. occcurrencedata or OccurrenceData, NOT occurrenceData); also note we have both connected names (occurrencedata) and also objects with underlines (species_list). Best if we use only one convention, not both of these. I suggest we delete the underlines (so change to SpeciesList)

**Comment by ccsosa** [comment]
I think this is done

**Comment by ccsosa** [comment]
Can I close this issue @ColinKhoury ?
