### ISSUE TITLE
Nora to rename her https://github.com/npcastaneda/gapAnalysis

### ISSUE THREAD

**Issue by ColinKhoury** [ccsosa/GapAnalysis#24]
To avoid confusion, shall we ask her to rename hers to gapanalysis_exsituonly or something?

**Comment by jramirezv** [comment]
That repo has no code. We should probably ask her to delete it to avoid confusion. Realistically she won’t really develop it.

**Comment by ColinKhoury** [comment]
Why did this get closed? I think it still has the old name (https://github.com/npcastaneda/gapAnalysis)

**Comment by jramirezv** [comment]
Not sure why it got closed. It's done now though. See https://github.com/npcastaneda/gapAnalysis_exsitu
