### ISSUE TITLE
Produce fig 1 (showing whole process diagram plus maps)

### ISSUE THREAD

**Issue by ColinKhoury** [ccsosa/GapAnalysis#27]
Need gap maps for one species

**Comment by ccsosa** [comment]
Can we meet and define how to do this?

**Comment by ColinKhoury** [comment]
I dont mind doing it. I just need the results for the cucurbita species (including all four gap maps)

**Comment by dcarver1** [comment]
@ColinKhoury I sent you some images built on the data from the publication. This is at 2.5 minute resolution. Let me know if you need any more materials for this. 

We're missing ERSin gap map at the moment due to an active issue. Once it is resolve we can get those maps out

**Comment by ColinKhoury** [comment]
I built some versions for the group to decide (sent by skype). Can finalize once I get your inputs. Still need to produce gap maps for ERSin and SRSin
