### ISSUE TITLE
optional function paraments - are they necessary (protect areas - ecoregion) 

### ISSUE THREAD

**Issue by dcarver1** [ccsosa/GapAnalysis#30]
The user is required to provide two components to run this package 
- a dataset of occurrence data with a set format
- a list of raster objects that are named to match the species names present in the occurrence data. 

I think it makes sense that these are the only two active inputs that are part of the functions. 

inSRS, inGRS, inERS, inFCS, exERS, exFCS all have parameters for protected areas, ecoregion or both. 

We provide these datasets as part of the package and this makes me think that we do not need to list them as parameters or keep them as optional variables (one that does not auto-populate when using ctrl+space in rstudio) 
see ?raster::area() 
x is required, the other options are '...' 
There are more options, you can include them by reading the documentation, but they don't present themselves actively. 

**I don't know how to make this change, but I'm sure I can find out** 

This feels largely like a cosmetic change, but I wanted to throw it out for other opinions.

**Comment by dcarver1** [comment]
As an example, 
```r 
#If I try to run FCSin without entering a parameter for Pro_areas, I get the following error. 
inFCS <- GapAnalysis::FCSin(Species_list = spList, Occurrence_data = data, Raster_list = r1,  Gap_MapIn = FALSE)
``` 
Error in GapAnalysis::FCSin(Species_list = spList, Occurrence_data = data,  : 
  argument "Pro_areas" is missing, with no default

This is occurring even with the following clause in the function 
```r
# load in protect area raster
  if(is.null(Pro_areas)){
    if(file.exists(system.file("data/preloaded_data/protectedArea/wdpa_reclass.tif",
                               package = "GapAnalysis"))){
      Pro_areas <- raster::raster(system.file("data/preloaded_data/protectedArea/wdpa_reclass.tif",
                                              package = "GapAnalysis"))
    } else {
      stop("Protected areas file is not available yet. Please run the function GetDatasets()  and try again")
    }
  } else{
    Pro_areas <- Pro_areas
  }
```

As the user I would either have to set this variable in the function parameters to NULL or point it to the GapAnalysys::ProtectedAreas object.  

The same error occurs with the ecoregion object/parameter

**Comment by ccsosa** [comment]
The solution is to include the default values in the function in this way:
GRSex <- function(Species_list, Occurrence_data, Raster_list, Buffer_distance=50000) {
..
...
}
