### ISSUE TITLE
ERSex function fails with example data 

### ISSUE THREAD

**Issue by dcarver1** [ccsosa/GapAnalysis#31]
When I run the ERSex using the example data I get the following error 

Error in GapAnalysis::ERSex(Species_list = spList, Occurrence_data = data,  : 
  object 'occDataG' not found

Just something that needs to be fixed. 

This also means that FCSex fails because it directly calls the ERSex function.

**Comment by ccsosa** [comment]
Fixed, It was an issue of vector names into the function.
