### ISSUE TITLE
Update the summary_html rmd file

### ISSUE THREAD

**Issue by ccsosa** [ccsosa/GapAnalysis#32]
Dear Dan, could you please update the rmd file used in summary_html function when we get the final code repo version?

Thanks

**Comment by dcarver1** [comment]
yes, I will do this after the ecological gap maps are complete

**Comment by dcarver1** [comment]
I'm pretty close on this... it's been requiring some minor adjustments within out scripts and troubleshooting is a little cumbersome. Hope to have something clean by Thursday

**Comment by dcarver1** [comment]
Waiting on some comments about the Text descrition of the gap maps. I'll need one for 
ERSin
ERSex 
and SRSin 

Things are looking good outside of that.

**Comment by jramirezv** [comment]
See issue #56 and once fixed update.

**Comment by dcarver1** [comment]
I did a big revision on the rmd. It's looking good. I posted copy of the output in skype and in #56 for review.

**Comment by dcarver1** [comment]
New element to review is tied into #56 
I'm closing this one out.
