### ISSUE TITLE
ERSin and ERSex -- use predicted presence based on SDM to generate list of ecoRegions

### ISSUE THREAD

**Issue by dcarver1** [ccsosa/GapAnalysis#33]
Rather than using the occurrence data for defining the total number of ecoregions that area present, I will be using the extent of the predicted presence based on the sdm. 

**this may change ERS values as predicted model presence may not cover all ecoregions used in the modeling process**  

Also, I am changing the selection category from ECO_NUM to ECO_ID_U as eco_id_ u is a unique value for each individual ecoregion and the eco_num is an aggregate of multiple eco_id_u 

Working on resolving this now, posting here mostly for record keeping

**Comment by ColinKhoury** [comment]
Note this is an enhancement and a fix- the original methodology was not really what was explained in our papers.

**Comment by dcarver1** [comment]
I asked @ccsosa to review the functionality of these scripts and then update documentation. He will be able to close this issue
