### ISSUE TITLE
Is it important that our examples match our published data? 

### ISSUE THREAD

**Issue by dcarver1** [ccsosa/GapAnalysis#36]
I believe we discussed this earlier and the answer was no, but I want to double-check. 

The SDM rasters from the dataverse are all clipped to mexico. This was done to reduce the overall size. 

![image](https://user-images.githubusercontent.com/32108872/82506585-6f002b80-9abd-11ea-9247-d820aa5ceea2.png)

In the case of Palmata and Digitata, all the G occurrences are from the united states. 

*image of Palmata*
![image](https://user-images.githubusercontent.com/32108872/82506634-91924480-9abd-11ea-8453-f5b5817a3be1.png)

Limiting the extent of the species distributions to Mexico means that most of the conservation metrics will be different for these two species (cordata has a no range in the US). 

I don't think this is a big issue though I believe it warrants a note in the readme or examples documentation that the conservation metrics within the examples do not represent the results from the published data. 

Any thoughts on this?

**Comment by jramirezv** [comment]
It’s just examples. It doesn’t matter if they aren’t real. I wouldn’t worry. If you want to include a note (tho i don’t think you need to) then do so but keep it short and without references to papers or other online material.

**Comment by ColinKhoury** [comment]
Hi,

I dont want to run these for just Mexico; doesnt make sense. Please include
USA.

C

*Colin Khoury*

Researcher │ Decision and Policy Analysis



*Alliance of Bioversity International and CIAT*

The Americas Hub

Km 17 Recta Cali-Palmira. C.P. 763537 - A.A. 6713, Cali, Colombia

✉ c.khoury@cgiar.org  📱  (+1) 970 237 9571 │ Skype colin.khoury  |
pronouns he/él <https://www.mypronouns.org/what-and-why>



████████████████████████████████████████████████████████████████



The *Alliance* of *Bioversity International* and the *International Center
for Tropical Agriculture (CIAT)*
delivers research-based solutions that harness agricultural biodiversity
and sustainably transform
food systems to improve people’s lives in a climate crisis.

The *Alliance* is part of *CGIAR*, a global research partnership for a
food-secure future.

*bioversityinternational.org*
<https://www.bioversityinternational.org/>
*ciat.cgiar.org* <https://ciat.cgiar.org/>

**Comment by jramirezv** [comment]
It’s for the package examples (the ones inside the actual R code documentation). Keep as is.

For the paper do as Colin says.

**Comment by ColinKhoury** [comment]
These are small distributions. Its not a huge data calculation cost. I think we should do it over full distribution

**Comment by ColinKhoury** [comment]
If you choose to keep only data for Mexico, then choose Mexican species- argyrosperma sororia, cordata, radicans, etc.

**Comment by jramirezv** [comment]
More data in there makes the examples, package data and package itself unnecessarily heavy. So, no, please dont. Keep as is. Light and simple. Most people would not even provide data, but generate random points just to illustrate a function.

**Comment by dcarver1** [comment]
I'd like to keep with these three species 

We can use the full extent of the rasters at a lower resolution and reduce the number of occurrences data for each species.
 
If we still have issues, It might be worth it to drop 1 taxon, this should drop overall time by 1/3. Also with two we still showcase the ability of the functions to work over a list of species. 
 
@ccsosa I can work on this today after I close out some of the issues from yesterday.

**Comment by ccsosa** [comment]
Please check if the resampled data to 10 min is OK. All taxa are between the US and Mexico.
