### ISSUE TITLE
reduce computation time in examples and make examples more consistent

### ISSUE THREAD

**Issue by jramirezv** [ccsosa/GapAnalysis#37]
Two actions:
– Make examples better (occurrences and species range are consistent)
– Make examples lighter to avoid the example execution time notes

**Comment by ccsosa** [comment]
I updated the examples files with 10 min resolution using ngb resampling. They are between the US and Mexico.  [digitata.pdf](https://github.com/ccsosa/GapAnalysis/files/4665677/digitata.pdf)
[palmata.pdf](https://github.com/ccsosa/GapAnalysis/files/4665678/palmata.pdf)
[wdpa.pdf](https://github.com/ccsosa/GapAnalysis/files/4665679/wdpa.pdf)
[cordata.pdf](https://github.com/ccsosa/GapAnalysis/files/4665680/cordata.pdf)
![image](https://user-images.githubusercontent.com/10407841/82623673-51f35780-9ba6-11ea-9726-6916ec7633db.png)

**Comment by ccsosa** [comment]
In the new push, there are no notes about examples execution time. Please check if it is ok to close this issue.
