### ISSUE TITLE
Enhance FCSc-mean by adding fields for priority categories for the FCSex and FCSin values

### ISSUE THREAD

**Issue by ColinKhoury** [ccsosa/GapAnalysis#38]
Currently priority categories (HP, MP, LP, SC) are assigned for c-mean, and for min, and for max. The dataframe contains the values for FCSex and FCSin, but priority categories based on these values are not given. It is nice to have them, though, because we often discuss conservation priorities for ex situ and in situ separately. Thus please add the priority categories for FCSex and FCSin into dataframe output

**Comment by ColinKhoury** [comment]
Note code for this is currently in the indicator code (lines 84-114); you might grab the code from there. When finalized, please remove that code from indicator code

**Comment by dcarver1** [comment]
Priority category has been added to FSCin and FCSex 
![image](https://user-images.githubusercontent.com/32108872/82611655-383e1a00-9b7e-11ea-9d19-7010ef8de48c.png)

Working on incorporating those elements into FCSc
