### ISSUE TITLE
FCSc-mean code- fix min and max names

### ISSUE THREAD

**Issue by ColinKhoury** [ccsosa/GapAnalysis#39]
Hi please make names FCS_min and FCS_max (not FCSc_min and FCSc_max); we arent combining so the little c doesnt make sense to have in the acronym.

**Comment by dcarver1** [comment]
Added FSCin and FCSex category values to the FCSc output dataframe 

![image](https://user-images.githubusercontent.com/32108872/82613148-d7b0dc00-9b81-11ea-8cc8-b2dcaa616cb6.png)

Also removed all the 'c' values from the column names. 
@ColinKhoury  if this looks good to you colin please close.

**Comment by ColinKhoury** [comment]
Looks good Dan. Note FCS_min and FCS_max are the enhancements we wanted (in terms of names), but we dont want to change FSCc_mean to FCS_mean. That is the combined one, so please change back to FCSc_mean, thanks

**Comment by dcarver1** [comment]
Ok, thanks for th clarification 
FCSc_mean is writen in 
![image](https://user-images.githubusercontent.com/32108872/82615659-30837300-9b88-11ea-8d68-a0c093aeb177.png)

I'll push these edits and close this issue.

**Comment by ccsosa** [comment]
I fixed a problem in indicators.R. I fixed it including an exclusion (if) for opt=3
