### ISSUE TITLE
Add raster in Depends DESCRIPTION

### ISSUE THREAD

**Issue by ccsosa** [ccsosa/GapAnalysis#41]
@jramirezv Should we add raster in Depends?
I noted that the package is working ok to calculate the maps but at the moment of plotting, etc... the raster package is not loaded. Basically this causes a possible error. This is easily fixed if the R package is load first. Should we add raster in Depends getting a warning or put in the tutorial? 

![image](https://user-images.githubusercontent.com/10407841/82741823-e9c68200-9d1b-11ea-9a73-ffb6c01eba18.png)

**Comment by jramirezv** [comment]
yes, please do so. Add raster in dependences.

**Comment by jramirezv** [comment]
I did so and tests passed on my Mac with R version 4.0.0. Please check and if it works for you close the issue.
