### ISSUE TITLE
accounting for different resolution between input SDM and protected areas Raster

### ISSUE THREAD

**Issue by dcarver1** [ccsosa/GapAnalysis#46]
We deliver the Protected areas raster at 0.04 degree cells. 
The user's SDM will be at some resolation, possible a different one. 

We need to resample the Protected Areas raster to apply raster math needed in SRSin plus others. 

Do we want to 
a, build in this resampling into our code? 
```r
    if(raster::res(Pro_areas1) != raster::res(sdm)){
      Pro_areas1 <- raster::resample(x = Pro_areas1, y = sdm)
    }
```
Or 
b. return a statement asking the user to resample the Protected area files themselves? 

I'm running with a for now, but maybe it makes sense for the user to make this adjustment?

**Comment by ccsosa** [comment]
I agree the user should make the change at least if they are not using the files provided by default.

**Comment by dcarver1** [comment]
So I included the code chunk above in SRSin, GRSin, and ERSin functions.
As we are providing the protected areas file via the dataverse I think it makes sense that we make the adjustment.  
I'll leave this open for @jramirezv to comment on if needed. But it's basically closed.

**Comment by jramirezv** [comment]
Ok for me
