### ISSUE TITLE
Should the four gap maps be calculating in FCSex and FCSin by adding Gap_Map=TRUE?

### ISSUE THREAD

**Issue by ccsosa** [ccsosa/GapAnalysis#48]
Nowadays, FCSin and FCSex are not producing the four maps due to that those codes produce tables. They are calculated in each specific step. Should we add Gap_Map parameter to switch and produce all those maps in a list when Gap_Map TRUE?

**Comment by jramirezv** [comment]
Makes sense.

**Comment by ccsosa** [comment]
I made the change including all maps for FCSex and FCSin. @dcarver1 Could you please check if it is working ok and fix any word if it is the case?
