### ISSUE TITLE
Error at install

### ISSUE THREAD

**Issue by jramirezv** [ccsosa/GapAnalysis#49]
Probably need to do `dont run` in the SummaryHTML example

See error log below.

* installing *source* package ‘GapAnalysis’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in SummaryHTML(Species_list = Species_list, Occurrence_data = Occurrence_data,  : 
  Rmd file is not available yet. Please run the function GetDatasets() and try again
Error: unable to load R code in package ‘GapAnalysis’
Execution halted
ERROR: lazy loading failed for package ‘GapAnalysis’
* removing ‘/Users/julian/Repositories/GapAnalysis/GapAnalysis.Rcheck/GapAnalysis’

**Comment by ccsosa** [comment]
Fixed
