### ISSUE TITLE
If there are no changes in code. Please check the manual to perform changes in documentation

### ISSUE THREAD

**Issue by ccsosa** [ccsosa/GapAnalysis#50]
Hi guys, if there are no more pending modifications. Could you please check the pdf manual version compiled by latex to do changes in documentation?

Thanks

This is the manual compiled by June 5th
[GapAnalysis-manual.pdf](https://github.com/ccsosa/GapAnalysis/files/4739353/GapAnalysis-manual.pdf)

**Comment by jramirezv** [comment]
Ok for me.
