### ISSUE TITLE
ensure gap map object names are standardized

### ISSUE THREAD

**Issue by ColinKhoury** [ccsosa/GapAnalysis#51]
I noticed the object names for GRS gap maps and ERS gap maps are a bit different (in their wording/structure). consider standardizing

**Comment by dcarver1** [comment]
hmm, thanks for catching this. Probably my fault I camelCase everything.

**Comment by ccsosa** [comment]
I added @dcarver1 names for ex-situ. New names are gap_maps for functions and for compiling functions are explicit as in-situ

**Comment by ccsosa** [comment]
I will close this, if it is something wrong, this issue will be reopened
