### ISSUE TITLE
Make species specific G buffer size 

### ISSUE THREAD

**Issue by ColinKhoury** [ccsosa/GapAnalysis#52]
Enable function where user can define G buffer size per species. (but of course keeping the 50km default) (for future release of GapAnalysis

**Comment by ccsosa** [comment]
@ColinKhoury the user can define the size, but the default value is 50000. Thus, if you change Buffersize in the example, you will see the change

**Comment by ColinKhoury** [comment]
I mean so that when you run a whole list of species, you can set the buffer easily for each species individually. Since the whole idea of user defined relates to different species having different amounts of genetic diversity based on their reproductive strategies, habitat heterogeneity, etc., the best solution in the long term is to enable each species to have its own buffer size (if knowledge exists), but still to keep gap analysis efficient by allowing users to run multiple species at the same time

**Comment by ccsosa** [comment]
I see your point, if you run each species in a loop.e.g. you can achieve this without modifying the code
species_name <- c("A","B","C")
x <- c(50000,10000,5000)
for(I in 1:length(species_name){
      GRSex_df <- GRSex(occurrences, raster,buffersize=x,Gap_Map=T)
}

**Comment by dcarver1** [comment]
If this is important, we should provide an example in the vignette.

**Comment by ccsosa** [comment]
I agree with @dcarver1, this issue can be solved with a good example in the vignette, and this can be sorted out for the user instead of us.

**Comment by ccsosa** [comment]
Can I close this issue?

**Comment by ccsosa** [comment]
I added a tutorial in the readme file that can manage this issue.
