### ISSUE TITLE
Make sure that Dataverse is ready

### ISSUE THREAD

**Issue by ColinKhoury** [ccsosa/GapAnalysis#54]
With no duplicates and everything clear to the user

**Comment by ccsosa** [comment]
https://dataverse.harvard.edu/dataverse/GapAnalysis
Please check if the repo is OK. It seems like dataverse is not working well for the repo changes.

I deaccessioned the SDMs and Rdata uploaded previously.

**Comment by jramirezv** [comment]
Ok for me. Reopen if anyone disagrees.
