### ISSUE TITLE
require packages in the RMD that are current not installed

### ISSUE THREAD

**Issue by dcarver1** [ccsosa/GapAnalysis#59]
Please add 

rgeos - popping as required for GRSex *not sure why that occurred for me?* 
kableExtra - using to format tables in the rmd 

to the required packages

**Comment by ccsosa** [comment]
Added kableExtra . rgeos error could be due to you are using R. 3.6. I will put rgeos as a dependency and try again.

**Comment by ccsosa** [comment]
Done, they are now in the DESCRIPTION file. check rgeos, I think is because of the R version.
