### ISSUE TITLE
add conditional statements that address the follow in all functions. 

### ISSUE THREAD

**Issue by dcarver1** [ccsosa/GapAnalysis#60]
from Julian email 

 no occurrence but has an SDM - error on the user end
 
no coordinates and no SDM - ranked as high priority 
- tricky as we need to assign values for the metrics that don't run... 

 if species has coordinates and smd the process runs effectively 
- basically the else at the end of the top two coditions. 

I'm fine with picking this one up. I might try to build functions that preform the test and return a binary. That should help keep the text within the functions down.

**Comment by dcarver1** [comment]
I resolved this by creating an internal function. I applied it after we call in the SDM in ERSex, ERSin, GRSex, GRSin, SRSin. SRSex does not require a SDM and the code should handle any issues with the dataframe as is  so I have not changed it. 

This a one of a few ways to do this be I thought is was the cleanest as it keeps the majority of the redundant code is in the function. 

I'll push these changes as a branch in case we find we need to go a different route. 

@ccsosa We can close and merge if you think this is acceptable.

**Comment by ccsosa** [comment]
Please  merge it

**Comment by ccsosa** [comment]
Merged and improved

**Comment by ccsosa** [comment]
Branches were merged
