### ISSUE TITLE
Clarify field names ERSex

### ISSUE THREAD

**Issue by jramirezv** [ccsosa/GapAnalysis#9]
In ERSex you assumes that occurrenceData will have two colunms named ‘longitude’ and ‘latitude’. But what if the user has the dataset named x y or lon lat? This may cause errors in the future. Maybe you should state in the argument description that xy must be named as longitude and latitude. Or lon lat for simplicity.

**Comment by ccsosa** [comment]
A statement was included to ensure your column names are following the template used in the example
